/** Generates docs/coverage.md from the ops manifest. Run: bun scripts/coverage-table.ts */
import { allOperations } from "../src/bridge/allowlist.ts";
import { OPS_MANIFEST } from "../src/ops-manifest.ts";

const rows = allOperations().map(({ domain, method }) => {
  const m = OPS_MANIFEST[domain]?.[method];
  const exposure = m
    ? m.action
      ? `\`${m.tool}\` → \`${m.action}\``
      : `\`${m.tool}\``
    : "**UNMAPPED**";
  return `| \`etch.${domain === "root" ? "" : `${domain}.`}${method}\` | ${exposure} |`;
});

const md = `# API Coverage — etchwp-ai

> Generated by \`bun scripts/coverage-table.ts\` from src/ops-manifest.ts.
> ${rows.length} documented \`0.x\` operations, 100% exposed. CI gate: test/coverage.test.ts.

| Etch Public API operation | MCP tool / action |
| ------------------------- | ----------------- |
${rows.join("\n")}

Notes:
- \`navigation.getActivePostId\` and \`navigation.isEditingTemplate\` surface as fields of \`etch_status\` (single read path).
- \`ui.exitToWordPress\` lives on \`etch_nav\` (confirm-gated, destroys the session).
- Extras beyond the raw API: \`etch_tokens\`, \`etch_screenshot\`, \`etch_insert_pattern\`, \`etch_history\` checkpoint/rollback, sidecar \`wp_media\`/\`wp_content\`.
`;

await Bun.write("docs/coverage.md", md);
console.log(`docs/coverage.md written (${rows.length} ops).`);
