/**
 * Live token export: scans the connected Etch builder page and writes its real
 * `:root` design tokens (ACSS + theme + Etch-registered) to a file. This is the
 * per-site, live half of the token story — the static default-name catalog lives
 * in src/acss/tokens.ts.
 *
 * Run: bun run scripts/export-tokens.ts [--format ts|json|css] [--filter acss|etch|custom|all] [--out <path>]
 *
 * It is a SCRIPT, not an MCP tool, on purpose: adding a tool would change the
 * "exactly 20 core tools" handshake gate and the coverage op count.
 */
import { type ClassifiedToken, classifyTokens } from "../src/acss/classify.ts";
import { CdpBridge } from "../src/bridge/cdp.ts";
import type { EtchBridge } from "../src/bridge/types.ts";
import type { Config } from "../src/config.ts";
import { loadConfig } from "../src/config.ts";

export type ExportFormat = "ts" | "json" | "css";
export type ExportFilter = "acss" | "etch" | "custom" | "all";

export interface ExportOptions {
  format: ExportFormat;
  filter: ExportFilter;
}

/** Serialize classified tokens into the requested format. Pure. */
export function serializeTokens(tokens: ClassifiedToken[], format: ExportFormat): string {
  if (format === "json") return `${JSON.stringify(tokens, null, 2)}\n`;
  if (format === "css") {
    const body = tokens.map((t) => `  ${t.name}: ${t.value};`).join("\n");
    return `:root {\n${body}\n}\n`;
  }
  // ts
  return (
    "// Generated by scripts/export-tokens.ts — live :root snapshot of the connected Etch page.\n" +
    'import type { ClassifiedToken } from "../src/acss/classify.ts";\n\n' +
    `export const LIVE_ACSS_TOKENS: ClassifiedToken[] = ${JSON.stringify(tokens, null, 2)};\n`
  );
}

/**
 * Testable core: attach the bridge, read the registry + computed `:root`, classify,
 * filter, and serialize. Works with the real CdpBridge or a MockBridge.
 */
export async function runExport(
  bridge: EtchBridge,
  config: Config,
  opts: ExportOptions,
): Promise<string> {
  await bridge.attach();
  const registry = ((await bridge.eval("styles", "listVariables")) ?? {}) as Record<string, string>;
  const computed = await bridge.readRootVariables();
  let tokens = classifyTokens(computed, registry, config.acssStylesheetPattern);
  if (opts.filter !== "all") tokens = tokens.filter((t) => t.classification === opts.filter);
  return serializeTokens(tokens, opts.format);
}

function parseArgs(argv: string[]): { opts: ExportOptions; out: string | null } {
  let format: ExportFormat = "json";
  let filter: ExportFilter = "acss";
  let out: string | null = null;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--format") format = argv[++i] as ExportFormat;
    else if (a === "--filter") filter = argv[++i] as ExportFilter;
    else if (a === "--out") out = argv[++i] ?? null;
  }
  if (!["ts", "json", "css"].includes(format)) throw new Error(`bad --format '${format}'`);
  if (!["acss", "etch", "custom", "all"].includes(filter))
    throw new Error(`bad --filter '${filter}'`);
  return { opts: { format, filter }, out };
}

async function main() {
  const { opts, out } = parseArgs(Bun.argv.slice(2));
  const config = loadConfig();
  const bridge = new CdpBridge(config);
  try {
    const output = await runExport(bridge, config, opts);
    if (out) {
      await Bun.write(out, output);
      console.error(`[export-tokens] wrote ${out} (format=${opts.format}, filter=${opts.filter}).`);
    } else {
      console.log(output);
    }
  } finally {
    await bridge.detach().catch(() => {});
  }
}

if (import.meta.main) {
  main().catch((e) => {
    console.error(`[export-tokens] error: ${e?.message ?? e}`);
    process.exit(1);
  });
}
